### ISSUE TITLE
[Feature]: Adding 2.0 to Forge

### ISSUE THREAD

**Issue by MattBanak** [tristankechlo/RandomMobSizes#10]
### What is your idea?

The new configuration options listed in the version 2.0 section of the wiki are _exactly_ what I want from this mod! I was so bummed to install on forge for 1.20.1 and see that the mod version on Forge isn't on 2.0 yet. Looking forward to that release!!

**Comment by MattBanak** [comment]
Alternatively, is there a way to set the "default scaling" with the old config?

**Comment by tristankechlo** [comment]
No, there is default scaling on the 'old' config.  
Version 2.0 is not yet released, I am currently testing a few things and will then bring the changes to other versions as well, before releasing them all.

**Comment by tristankechlo** [comment]
Version 2.0 is now released for 1.18.2, 1.19.4, 1.20.1 and 1.20.4
