### ISSUE TITLE
[Feature]: Mob death loot scaling based on size

### ISSUE THREAD

**Issue by MattBanak** [tristankechlo/RandomMobSizes#11]
### What is your idea?

New scaling was added for 2.0+ for a few mob attributes based on the size of the mob. It'd be really cool if the size of the mob also impacted the average amount of dropped items. I think this is a good idea because intuitively as a player, when I kill an oversized cow it _feels_ like I should get more meat for example. 

I have zero idea how feasible this idea is. Love the mod! Also +1 to the genetic sizes suggestion, if we get that change and this one then it'd add a lot of fun and realistic depth to mob farming!

**Comment by tristankechlo** [comment]
Thank you for your suggestion, the idea sounds interesting and I will see if I can implement something like this

**Comment by tristankechlo** [comment]
Note to myself: If this gets implemented, the amount of dropped xp should scale with the mob size as well

**Comment by tristankechlo** [comment]
Scaling of loot and experience is with version 2.0 now possible.
