### ISSUE TITLE
[Bug]: Broken hitboxes

### ISSUE THREAD

**Issue by A5ho9999** [tristankechlo/RandomMobSizes#13]
### What happened?

Mod causes issues with normal entity hitboxes, for example 

- Magma Cubes have larger hitbox no matter their size. (This can cause froglight farms to break by dying magma cubes being forced through the walls). 
- Pufferfish don't change size when bloated (this breaks normal game like pufferfish doors)

Video files were too big to add (and weren't embedding)

[Video without mod](https://cdn.discordapp.com/attachments/1177899790948892723/1178550418603790337/Minecraft__1.20.1_-_Singleplayer_2023-11-26_22-17-47.mp4?ex=65768d9c&is=6564189c&hm=e39c081b357010341f5c66b894d3b77de76c080133644f8a0e634b18ca4a450f&)

[Video with Mod](https://cdn.discordapp.com/attachments/1177899790948892723/1178550421573345290/Minecraft__1.20.1_-_Singleplayer_2023-11-26_22-01-38.mp4?ex=65768d9c&is=6564189c&hm=1584e05656eb69c183347be86cc8e85d076ec7812e1655c176bfd1b0e6829b0e&)

### Minecraft Version

1.20.1

### Modversion

https://modrinth.com/mod/random-mob-sizes/version/1.20.1-1.3-Fabric

### Modloader

Fabric

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thank you for reporting, I will look into it

**Comment by A5ho9999** [comment]
Would you possibly have a timeframe? We'll be updating our server in a couple weeks and will have to unfortunately remove the mod if not looked into before then.

**Comment by tristankechlo** [comment]
Sorry, no timeframe  
I have a general idea what might cause this, but not really sure how to fix it

**Comment by DedMaxim** [comment]
Can add spiders to the list. No matter what size they have, hitbox stays the same. Yet, the line of sight's position get changed. So if a spider is very big, its line of sight is very high above the hitbox and it can suffocate easily.

Edit: In my case, the mod loader is Forge 1.19.2 43.3.2

An example of such big spider with tiny hitbox and a line of sight inside of its body:
![image](https://github.com/tristankechlo/RandomMobSizes/assets/41780875/ed93a8ec-f828-4298-8d03-b9db85b5d431)
![image](https://github.com/tristankechlo/RandomMobSizes/assets/41780875/6b1dd1c0-9892-42aa-a53e-5ef7544b85c3)

**Comment by A5ho9999** [comment]
I had a quick play around and appears to be the refreshDimensions [mainly this line](https://github.com/tristankechlo/RandomMobSizes/blob/e8f450e670e0d283f485c561b32adbeaef27bc98/Common/src/main/java/com/tristankechlo/random_mob_sizes/mixin/EntityMixin.java#L46C52-L46C52). I replaced with `EntityDimensions dimensions = entity.getDimensions(pose);` which seemed to fix the main issue but seems to break hitboxes on baby entity.

Edit:
After bit more playing, above slightly fixed by the hitboxes are still incorrect (too small). I decided to just remove the whole refreshDimensions section which seems to work fine and all hitboxes are correct. What is the purpose of this mixin?

**Comment by tristankechlo** [comment]
Originally I had problems with hitboxes for slimes, when they die/split-up and get smaller.  
The mixin was there to counter these issues, but that's some time ago, maybe the mixin is unnecessary by now.  
Thanks for testing/debugging, will look into it as soon as I have time

**Comment by tristankechlo** [comment]
Version 2.0 was just released, the scaling issue should be fixed now
