### ISSUE TITLE
[Bug]: Config keeps shuffling and randomly removing values

### ISSUE THREAD

**Issue by katubug** [tristankechlo/RandomMobSizes#14]
### What happened?

I'm not sure when exactly this happens, but it occurs frequently, possibly every time I restart my client. It's happening a lot, as I'm doing modpack dev stuff at the moment.

What happens is that the entire config rejigs itself, which sometimes just results in values being swapped, but other times results in values being lost, as you can see here: https://i.imgur.com/dHF3eRJ.png

Is there a way of ensuring that the config file stays static? Or is there another way to add entries which is less volatile? Thanks!

### Minecraft Version

1.20.1

### Modversion

1.3

### Modloader

Forge

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
> What happens is that the entire config rejigs itself, which sometimes just results in values being swapped

While testing the mod, I noticed that too, but sadly I could never figure out how to prevent that  
<hr/>  
  
> but other times results in values being lost

if there are problems while loading, some values are removed, the reason why entries are removed should be printed in the logs
<hr/>  
  
> Is there a way of ensuring that the config file stays static?

not at this moment, sorry
<hr/>  
  
> Or is there another way to add entries which is less volatile?

the values can be modified ingame, through the command `/mobScalings`,  
https://github.com/tristankechlo/RandomMobSizes/wiki/Commands#mobscalings

**Comment by tristankechlo** [comment]
Config values are now (version 2.0) sorted alphabetical
