### ISSUE TITLE
[Bug] [1.20.1]: Baby Mob Sizes

### ISSUE THREAD

**Issue by Sandriell** [tristankechlo/RandomMobSizes#15]
### What happened?

Baby mobs are either not always respecting the scaling or not getting scaled at all. 

One baby I noticed that does not seem to scale is baby bees. Despite having a range set for bees, the babies always spawn at the same size.

Additionally, when a size range is used, the baby can sometimes end up larger than the parent, which just looks.. weird. Babies should always fall at the minimum scaling size, or even just below it.

### Minecraft Version

1.20.1

### Modversion

randommobsizes-forge-1.20.1-2.0

### Modloader

Forge

### Additional context

```
    "minecraft:bee": {
      "type": "uniform",
      "max_scaling": 0.3,
      "min_scaling": 0.2,
      "scale_loot": false,
      "scale_xp": false,
      "scale_health": "none",
      "scale_damage": "none",
      "scale_speed": "none"
    },
```

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thanks for reporting this issue,  
will have a look why they are not scaled correctly.  
  
---
   
> Additionally, when a size range is used, the baby can sometimes end up larger than the parent, which just looks.. weird. Babies should always fall at the minimum scaling size, or even just below it.

Noticed that while playing, I am not sure how to handle this yet. I think it's funny when they are larger than their parents, but I can see why this can be annoying.  
It would probably be best to make it an option in the config, so that people can choose for themselves.

**Comment by tristankechlo** [comment]
Version 2.1 was just released, baby mobs should now scale correctly,
at the moment there is **not** an option to choose whether the baby ones should scaled
