### ISSUE TITLE
[Bug] [1.20.1]: Caves Spiders Don't Scale

### ISSUE THREAD

**Issue by Sandriell** [tristankechlo/RandomMobSizes#16]
### What happened?

Cave spiders do not seem to be getting scaled at all. Normal spiders scale properly.

![2024-03-25_23 01 41](https://github.com/tristankechlo/RandomMobSizes/assets/10704907/affe9f72-775b-4c37-abc9-ddf80832b222)

Shown here all the same vanilla size, despite having a wide size range set

### Minecraft Version

1.20.1

### Modversion

randommobsizes-forge-1.20.1-2.0

### Modloader

Forge

### Additional context

```
      "minecraft:cave_spider": {
      "type": "uniform",
      "min_scaling": 0.3,
      "max_scaling": 1.0,
      "scale_loot": true,
      "scale_xp": true,
      "scale_health": "normal",
      "scale_damage": "none",
      "scale_speed": "inverse"
		},
```

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thanks for reporting this issue,  
already fixed this in the source code, so the next update should solve this

**Comment by tristankechlo** [comment]
Version 2.1 was just released, the scaling issue should be fixed now
