### ISSUE TITLE
[Bug]: Latest Version does not run under 1.19.3

### ISSUE THREAD

**Issue by Cape-City** [tristankechlo/RandomMobSizes#18]
### What happened?

The latest version presented within CurseForge under my 1.19.3 profile requires 1.19.4 instead:

![grafik](https://github.com/tristankechlo/RandomMobSizes/assets/122229367/d239ed84-060b-43df-acad-523fed5f0375)

### Minecraft Version

1.19.3

### Modversion

randommobsizes-fabric-1.19.4-2.1.jar

### Modloader

Fabric

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thank you for reporting, I just changed the tags.
The file is now only listed for 1.19.4
