### ISSUE TITLE
[question] 1.19.2 Modded mobs aren't affected, is this normal?

### ISSUE THREAD

**Issue by netcore10** [tristankechlo/RandomMobSizes#2]
Modded mobs don't seem to be affected, is this normal?

**Comment by tristankechlo** [comment]
depends, if the mobs are made with geckolib, then yes there were some incompatibilities  
(this was fixed in newer modversions, but not for 1.19.2)  
  
if the models are not made with geckolib, then they should work

**Comment by netcore10** [comment]
Ah, that explains it, i'm stuck on 1.19.2. I take it a backport of the fix isn't planned?

**Comment by tristankechlo** [comment]
It wasn't on my plan, but I might consider it in the future

**Comment by netcore10** [comment]
Thank you for even considering it, i appreciate the gesture regardless.

**Comment by tristankechlo** [comment]
so I just ported the geckolib support to the 1.19.2 version of the mod,  
can you have another look to see if this solves your problem?

**Comment by netcore10** [comment]
This works! Thank you so much for the backport.
