### ISSUE TITLE
[Feature]: Scale the toothpicks 🏹 

### ISSUE THREAD

**Issue by DemonSlayer112** [tristankechlo/RandomMobSizes#21]
### What is your idea?

Its cool and all to see large skeletons, but its silly when the small guys fire arrows twice the height they are, but even weirder to see a huge skeleton fire a toothpick sized arrow from him.
Could be cool to see a large huge arrow, perhaps it could cause more damage?

Ps, perhaps also something for vehicles? Like Boats and minecarts? For those who configure the pack i mean, not by default ofc xD

**Comment by tristankechlo** [comment]
Definitely an interesting idea, but I will probably not implement it.
For future versions I am aiming to make the mod fully server-side only, and scaling the other entities than mobs will not be possible then.
