### ISSUE TITLE
[Bug] Trying to breed frogs crashes the game

### ISSUE THREAD

**Issue by zukitbh** [tristankechlo/RandomMobSizes#22]
### What happened?

When trying to breed frogs, game crashes when the frog eggs spawn in. Error in error log says:

> 
>java.lang.NullPointerException: Cannot invoke "com.tristankechlo.random_mob_sizes.mixin_helper.MobMixinAddon.doFinalizeSpawn$RandomMobSizes(net.minecraft.class_5425)" because "child" is null
> 	at net.minecraft.class_1429.handler$coj000$random_mob_sizes$finalizeSpawnChildFromBreeding$RandomMobSizes(class_1429.java:518)
> 	at net.minecraft.class_1429.method_49794(class_1429.java)
> 	at net.minecraft.class_7102.method_24650(class_7102.java:282)
> 	at net.minecraft.class_4806.method_24549(class_4806.java:89)
> 	at net.minecraft.class_4806.method_18924(class_4806.java:17)
> 	at net.minecraft.class_4097.method_18923(class_4097.java:66)
> 	at net.minecraft.class_4095.method_19545(class_4095.java:548)
> 	at net.minecraft.class_4095.method_19542(class_4095.java:493)
> 	at net.minecraft.class_7102.method_5958(class_7102.java:201)
> 	at net.minecraft.class_1308.method_6023(class_1308.java:847)
> 	at net.minecraft.class_1309.method_6007(class_1309.java:2789)
> 	at net.minecraft.class_1308.method_6007(class_1308.java:603)
> 	at net.minecraft.class_1296.method_6007(class_1296.java:128)
> 	at net.minecraft.class_1429.method_6007(class_1429.java:57)
> 	at net.minecraft.class_1309.method_5773(class_1309.java:2529)
> 	at net.minecraft.class_1308.method_5773(class_1308.java:377)
> 	at net.minecraft.class_7102.method_5773(class_7102.java:217)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:769)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:492)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:407)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:371)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:998)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:113)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at net.minecraft.class_1429.handler$coj000$random_mob_sizes$finalizeSpawnChildFromBreeding$RandomMobSizes(class_1429.java:518)
> 	at net.minecraft.class_1429.method_49794(class_1429.java)
> 	at net.minecraft.class_7102.method_24650(class_7102.java:282)
> 	at net.minecraft.class_4806.method_24549(class_4806.java:89)
> 	at net.minecraft.class_4806.method_18924(class_4806.java:17)
> 	at net.minecraft.class_4097.method_18923(class_4097.java:66)
> 	at net.minecraft.class_4095.method_19545(class_4095.java:548)
> 	at net.minecraft.class_4095.method_19542(class_4095.java:493)
> 	at net.minecraft.class_7102.method_5958(class_7102.java:201)
> 	at net.minecraft.class_1308.method_6023(class_1308.java:847)
> 	at net.minecraft.class_1309.method_6007(class_1309.java:2789)
> 	at net.minecraft.class_1308.method_6007(class_1308.java:603)
> 	at net.minecraft.class_1296.method_6007(class_1296.java:128)
> 	at net.minecraft.class_1429.method_6007(class_1429.java:57)
> 	at net.minecraft.class_1309.method_5773(class_1309.java:2529)
> 	at net.minecraft.class_1308.method_5773(class_1308.java:377)
> 	at net.minecraft.class_7102.method_5773(class_7102.java:217)
> 	at net.minecraft.class_3218.method_18762(class_3218.java:769)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:492)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:407)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: minecraft:frog (net.minecraft.class_7102)
> 	Entity ID: 10498
> 	Entity Name: Frog
> 	Entity's Exact location: 1438.88, 64.00, 299.75
> 	Entity's Block location: World: (1438,64,299), Section: (at 14,0,11 in 89,4,18; chunk contains blocks 1424,-64,288 to 1439,319,303), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,-64,0 to 1535,319,511)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: null
> Stacktrace:
> 	at net.minecraft.class_1937.method_18472(class_1937.java:492)
> 	at net.minecraft.class_3218.method_31420(class_3218.java:407)
> 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:371)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:998)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:113)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_3222['zukiTBH'/16, l='ServerLevel[Modded 1 20 6 solo]', x=1440.63, y=64.00, z=300.18]]
> 	Chunk stats: 3770
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (208,71,208), Section: (at 0,7,0 in 13,4,13; chunk contains blocks 208,-64,208 to 223,319,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
> 	Level time: 367580 game time, 529883 day time
> 	Level name: Modded 1 20 6 solo
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: true
> 	Level weather: Rain time: 9629 (now: false), thunder time: 113996 (now: false)
> 	Known server brands: fabric
> 	Removed feature flags: 
> 	Level was modded: true
> 	Level storage version: 0x04ABD - Anvil
> 	Loaded entity count: 342
> Stacktrace:
> 	at net.minecraft.class_3218.method_8538(class_3218.java:1710)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1001)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889)
> 	at net.minecraft.class_1132.method_3748(class_1132.java:113)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Minecraft Version

1.20.6

### Modversion

randommobsizes-fabric-1.20.6-2.1

### Modloader

Fabric

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
probably same as #20

**Comment by tristankechlo** [comment]
should be fixed with the newest version of the mod
