### ISSUE TITLE
[Bug]: No loot when "scale_loot": false, for generic setting

### ISSUE THREAD

**Issue by Atlasuser1** [tristankechlo/RandomMobSizes#23]
### What happened?

No mobs drop loot when scale loot is off. This is my config setup:

<details>
<summary>config.json</summary>

```json
{
	"default_scaling": {
		"type": "gaussian",
		"min_scaling": 0.6,
		"max_scaling": 1.2,
		"close_to_original": true,
		"scale_loot": false,
		"scale_xp": false,
		"scale_health": "none",
		"scale_damage": "none",
		"scale_speed": "none"
	},
	"include_list": [
		"minecraft:*"
	],
	"exclude_list": [
		"minecraft:shulker",
		"minecraft:wither"
	],
	"keep_scaling_on_conversion": true,
	"scaling_overrides": {}
}
```

</details>

### Minecraft Version

1.21

### Modversion

2.2.0

### Modloader

Fabric

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thank you for reporting.
I will have a look into this.

**Comment by tristankechlo** [comment]
error confirmed, seems to affect all active branches/versions  
tracker on which branches this has been fixed:  
- [x] 1.21
- [x] 1.20.6
- [x] 1.20.4
- [x] 1.20.1
- [x] 1.19.4
- [x] 1.18.2

**Comment by tristankechlo** [comment]
should be fixed in all major versions
