### ISSUE TITLE
[Bug]: randommobsizes-fabric-1.20.1-2.2.2.jar Crash

### ISSUE THREAD

**Issue by NFLD99** [tristankechlo/RandomMobSizes#26]
### What happened?

randommobsizes-fabric-1.20.1-2.2.2.jar crashes on start

### Minecraft Version

1.20.1

### Modversion

2.2.2

### Modloader

Fabric

### Additional context

[latest.log](https://github.com/user-attachments/files/17303755/latest.log)
tested with only RMS

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Thank you for reporting, it took me some time to decypher those useless fabric logs, but I think I got it now.
Will see if I can reproduce and fix the error.

**Comment by NFLD99** [comment]
> Thank you for reporting, it took me some time to decypher those useless fabric logs, but I think I got it now.
> Will see if I can reproduce and fix the error.

Unfortunately it didn't produce any crash logs, however that log is with only RMS installed

**Comment by tristankechlo** [comment]
should be fixed with the newest version (1.20.1-2.2.3)

**Comment by NFLD99** [comment]
All seems good on that version
