### ISSUE TITLE
[Feature]: More types to set for spawn rates.

### ISSUE THREAD

**Issue by ALainxD** [tristankechlo/RandomMobSizes#4]
### What is your idea?

right now we have 
- uniform - will cause the scaling factor to be evenly distributed between the min and max scaling
- gaussian - will cause the scaling factor to be distributed according to a gaussian distribution. This causes that most mobs will spawn with a scaling factor close to the center of the min and max scaling. So the extreme large and small mobs will spawn less often.

I would suggest adding:

- close to original: If you set the scale from 0.8 to 2.5 it will still spawn most of them close to 1 but have really small chances to get up to 2.5, with gaussian you would get a average of 1.65 and not 1.

- Random: chooses randomly numbers in the set range all the time. If I understand uniform correctly it is not random, you will always have big mobs next to small ones.

- difficulty - depending on the ingame difficulty it will spawn hostile mobs more often in a small variant if set on hard and big ones more often in a easy difficulty.

Especially close to original would be my most wanted one. For example when I change the size of bats I don't want them to be much smaller than original but they can get really big, with the close to original they would still mostly spawn around 1 but rarely get really big.

Really cool mod btw enjoing it so far.

### Additional context

Minecraft 1.18.2 Forge

**Comment by ALainxD** [comment]
Also something else to add: it would be good if you already list up all vanilla mobs in the config file so people don't have to type them in manually, the range could also be set to 1 - 1 so it won't change anything unless the player changes it.

**Comment by tristankechlo** [comment]
Thanks for the ideas  
  
 - close to original: interesting idea, will see what I can do to implement it
 - random: this is actually how the uniform works, random numbers inside the given range (wiki explanation might be confusing, I will update that)
 - difficulty: not really sure what the point of this is. Make them harder/easier to hit on different difficulties?

<hr>  
  
I like your idea for the default values for the config, I was thinking of adding all entities but did not think of just setting the value to 1

**Comment by tristankechlo** [comment]
With the newest update (2.0) the `close_to_original` option was added to the gaussian scaling.  
Additionally a scaling based on the difficulty was added.
