### ISSUE TITLE
[Feature]: Convenient config

### ISSUE THREAD

**Issue by Kirisoup** [tristankechlo/RandomMobSizes#6]
### What is your idea?

I might be asking for too much, please feel no pressure at all! 

It would be convenient if that the mobs to be scaled can be selected by whitelist and also blacklist mode, and if users can specify a default random scaling setting which applies to all the scaled mobs unless if the mob's scaling setting is specified individually.

Thank you!

**Comment by tristankechlo** [comment]
This is a great idea, that was requested by multiple people.  
I am actually currently working to implement something like this 👍

**Comment by tristankechlo** [comment]
With the newest update (2.0) a default scaling with include/exclude list was added.
