### ISSUE TITLE
[Bug]: Can't Join Servers

### ISSUE THREAD

**Issue by dophire** [tristankechlo/RandomMobSizes#7]
### What happened?

When I have the mod installed, I cannot join any multiplayer servers. I get immediately kicked otu with the following error.
![2023-09-29_17 57 04](https://github.com/tristankechlo/RandomMobSizes/assets/38838633/b213a334-1a79-42f3-9014-144f650174d9)

I also attached a manually generated crash log if it would help. (the mod doesn't crash my game, it's just for additional info)
[crash-2023-09-29_17.57.20-client.txt](https://github.com/tristankechlo/RandomMobSizes/files/12772564/crash-2023-09-29_17.57.20-client.txt)

### Minecraft Version

1.20.1

### Modversion

randommobsizes-fabric-1.20.1-1.3

### Modloader

Quilt

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
So the thing is, the mod is not explicitly made for quilt. Might be just incompatible.  
I've kinda never bothered with quilt. I never tested it and probably never will.  
  
But maybe I can give you a little help anyway...  
Has the server also the mod installed? Do the server and your client have the same mod version?  
A little more helpful than the crash-log, are the error messages in the log that appear when you try to join a server.

**Comment by dophire** [comment]
No, none of the servers have the mod, they're just regular servers (hypixel, survival, or any other server). This mod simply prevents me from joining any multiplayer server. Without the mod - everything works fine. Here's the latest log after joining a server.
[latest.log](https://github.com/tristankechlo/RandomMobSizes/files/12775513/latest.log)

**Comment by tristankechlo** [comment]
Well, than that's where the problem is, the mod needs to be installed on the client and server.  
If you want to play on non modded servers, it can't be with this mod installed.

**Comment by dophire** [comment]
Isn't there a way to disable the mod whenever you join a server? To run a check if the server has the mod, and if it doesn't - disable the mod for the time when you're on a server, and enable it when you leave it. That would be much appreciated!

**Comment by tristankechlo** [comment]
That's not possible with how this mod works.  
It adds new data attributes to the mobs. Those attributes are synced from server to client by minecraft and not by this mod.  
So this mod needs to be installed on both server and client to function properly (as most mods do).
