### ISSUE TITLE
[Bug]: Incompatible with Tarterzens

### ISSUE THREAD

**Issue by maiguel5** [tristankechlo/RandomMobSizes#9]
### What happened?

If u have tarterzens installed and some npc created, installing RandomMobSizes in the same server will destroy all existing npc (lucky me i always make backups, was so scary)

### Minecraft Version

1.19.2

### Modversion

randommobsizes-fabric-1.19.2-1.3

### Modloader

Fabric

### Additional context

admin a server hard modded, we have so many npc and testing to add your mod discovered that all npc were gone for some reason (other entities by the way, survive)
loaded from backup and tried a few times, the world will load except that the previus npc will disappear.
You still can create new ones, but it makes no sense when you have a big world build.

(My english is bad, sorry in advance)

Test was done in taterzens-1.11.0-fabric for more context.

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
I will look into it and see what I can do
